### PR TITLE
version in master setup.py should be bumped to 1.0.6 

### PR DESCRIPTION
**Pull request by trown**
Fixes issue #27

### CODE REVIEW

**Comment by rockymeza** [comment]
Hi @trown,

Thanks for catching this! For some of our projects, we've actually been moving the version number up in master so that we don't have to edit it with every patch. I'm thinking that we could do that here. Could you set the version to 1.1.0 instead of 1.06?

Thanks again!

**Comment by trown** [comment]
Hi @rockymeza,

I made the suggested change to 1.1.0. Thanks for looking at this.

**Comment by rockymeza** [comment]
Thanks @trown.

**Comment by rockymeza** [comment]
Thanks @trown.

**Pull request merged**
